// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthSqZAfSyNNsuaVI9XIbVrYd0CdF-vdA',
    appId: '1:357230998124:web:8cf60a9dc31c630583de49',
    messagingSenderId: '357230998124',
    projectId: 'untitled1-b94c0',
    authDomain: 'untitled1-b94c0.firebaseapp.com',
    storageBucket: 'untitled1-b94c0.firebasestorage.app',
    measurementId: 'G-YWR1JQLX0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1INZfV8ubx7E7loPYoPOOAeTB4mTSxo',
    appId: '1:357230998124:android:57b3476142b528b883de49',
    messagingSenderId: '357230998124',
    projectId: 'untitled1-b94c0',
    storageBucket: 'untitled1-b94c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8_bN6166JH52qlbINWnnrwu3FFeAytM',
    appId: '1:357230998124:ios:240449535bcc0f0f83de49',
    messagingSenderId: '357230998124',
    projectId: 'untitled1-b94c0',
    storageBucket: 'untitled1-b94c0.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8_bN6166JH52qlbINWnnrwu3FFeAytM',
    appId: '1:357230998124:ios:240449535bcc0f0f83de49',
    messagingSenderId: '357230998124',
    projectId: 'untitled1-b94c0',
    storageBucket: 'untitled1-b94c0.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthSqZAfSyNNsuaVI9XIbVrYd0CdF-vdA',
    appId: '1:357230998124:web:5520036f74ce404683de49',
    messagingSenderId: '357230998124',
    projectId: 'untitled1-b94c0',
    authDomain: 'untitled1-b94c0.firebaseapp.com',
    storageBucket: 'untitled1-b94c0.firebasestorage.app',
    measurementId: 'G-2FX6HDJLC3',
  );
}
